# action.yml
name: 'Build IBAMR'
description: 'Build the IBAMR libraries and test suite.'
runs:
  using: 'docker'
  image: 'docker://dcthomp/ibamr:0.9-build-deps'
  args:
    - /bin/bash
    - -c
    - "./.github/actions/build-ibamr/test-build"
