on:
  # Trigger the workflow on push or pull request,
  # but only when targeting the main branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_ibamr:
    runs-on: ubuntu-latest
    name: Test whether IBAMR builds
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build IBAMR
        uses: ./.github/actions/build-ibamr/ # Uses the action in this directory
        id: build
