## ---------------------------------------------------------------------
##
## Copyright (c) 2021 - 2021 by the IBAMR developers
## All rights reserved.
##
## This file is part of IBAMR.
##
## IBAMR is free software and is distributed under the 3-clause BSD
## license. The full text of the license can be found in the file
## COPYRIGHT at the top level directory of IBAMR.
##
## ---------------------------------------------------------------------

name: Pull/push
on:
  # Trigger the workflow on push or pull request,
  # but only when targeting the main branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  # build IBAMR with CMake and run tests
  build_ibamr:
    runs-on: ubuntu-latest
    name: Build IBAMR and run tests
    container:
      image: 'docker://dcthomp/ibamr:0.9-build-deps'
    env:
      # For now, hardwire the configuration since we have only one.
      # This is used by ctest_configure.cmake to initialize the
      # CMake cache by including
      # `.github/cmake/configure_${CMAKE_CONFIGURATION}.cmake`
      # so it is possible to run the same container with different
      # values to build different configurations (e.g., release vs
      # debug, with/without in situ processing, static analysis).
      CMAKE_CONFIGURATION: fedora33

      # If this variable is set, cause any build warnings to
      # be treated as an error (causing the build to fail before
      # testing and preventing merging).
      CTEST_NO_WARNINGS_ALLOWED: true

      CMAKE_GENERATOR: Unix Makefiles
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
        id: git
      - name: Create keys
        id: keys
        run: |
          echo "::set-output name=key1::$(( ${{ github.run_number }} - 1))"
          echo "::set-output name=key2::$(( ${{ github.run_number }} - 2))"
          echo "::set-output name=key3::$(( ${{ github.run_number }} - 3))"
          echo "::set-output name=key4::$(( ${{ github.run_number }} - 4))"
          echo "::set-output name=key5::$(( ${{ github.run_number }} - 5))"
      - name: Populate sccache
        uses: actions/cache@v2
        env:
          cache-name: sccache
        id: cache
        with:
          path: ~/.cache/sccache
          # A fundamental problem with the cache is that it is identified by a
          # single key and, should a cache with that key already exist, the
          # cache will not be updated. This makes sense for things like NPM but
          # not so much for sccache, since we get a new and unique cache each
          # time we rebuild the library with a new branch.
          #
          # To get around this, always make the key unique and rely on
          # restore-keys to find the highest-indexed key available. Explicitly
          # try to restore things from the most recent builds.
          key: ${{ runner.os }}-build-${{ github.run_number }}
          restore-keys: |
            ${{ runner.os }}-build-${{ steps.keys.outputs.key1 }}
            ${{ runner.os }}-build-${{ steps.keys.outputs.key2 }}
            ${{ runner.os }}-build-${{ steps.keys.outputs.key3 }}
            ${{ runner.os }}-build-${{ steps.keys.outputs.key4 }}
            ${{ runner.os }}-build-${{ steps.keys.outputs.key5 }}
            ${{ runner.os }}-build-
      - name: Start sccache server
        id: cache-server
        run: sccache --start-server
      - name: Configure IBAMR
        id: configure
        run: |
          bash -c "ctest -VV -S .github/cmake/ctest_configure.cmake"
          sccache --show-stats
      - name: Compile IBAMR
        id: build
        run: |
          bash -c "ctest -VV -S .github/cmake/ctest_build.cmake"
          sccache --show-stats
      - name: Test IBAMR
        id: test
        # run: ${{ LAUNCHER }} ctest --output-on-failure -V -S .github/cmake/ctest_test.cmake
        run: |
          bash -c "ctest --output-on-failure -VV -S .github/cmake/ctest_test.cmake"
          sccache --show-stats

  # build IBAMR with CMake, no libMesh, and run tests
  build_ibamr_no_libmesh:
    runs-on: ubuntu-latest
    name: Build IBAMR and run tests (no libMesh)
    container:
      image: 'docker://dcthomp/ibamr:0.9-build-deps'
    env:
      CMAKE_CONFIGURATION: fedora33_no_libmesh

      # If this variable is set, cause any build warnings to
      # be treated as an error (causing the build to fail before
      # testing and preventing merging).
      CTEST_NO_WARNINGS_ALLOWED: true

      CMAKE_GENERATOR: Unix Makefiles
    steps:
      - name: Generate id that is probably unique
        id: generate_id
        run:  echo "::set-output name=id::$RANDOM"
      - name: Checkout Source
        uses: actions/checkout@v2
        id: git
      - name: Create keys
        id: keys
        run: |
          echo "::set-output name=key1::$(( ${{ github.run_number }} - 1))"
          echo "::set-output name=key2::$(( ${{ github.run_number }} - 2))"
          echo "::set-output name=key3::$(( ${{ github.run_number }} - 3))"
          echo "::set-output name=key4::$(( ${{ github.run_number }} - 4))"
          echo "::set-output name=key5::$(( ${{ github.run_number }} - 5))"
      - name: Populate sccache
        uses: actions/cache@v2
        env:
          cache-name: sccache
        id: cache
        with:
          path: ~/.cache/sccache
          # 1 of 2: We don't want to ever restore this cache so pick a very unique name
          key: ${{ runner.os }}-build-no-libmesh-${{ steps.generate_id.outputs.id }}
          restore-keys: |
            ${{ runner.os }}-build-${{ steps.keys.outputs.key1 }}
            ${{ runner.os }}-build-${{ steps.keys.outputs.key2 }}
            ${{ runner.os }}-build-${{ steps.keys.outputs.key3 }}
            ${{ runner.os }}-build-${{ steps.keys.outputs.key4 }}
            ${{ runner.os }}-build-${{ steps.keys.outputs.key5 }}
            ${{ runner.os }}-build-
      - name: Start sccache server
        id: cache-server
        run: sccache --start-server
      - name: Configure IBAMR
        id: configure
        run: |
          bash -c "ctest -VV -S .github/cmake/ctest_configure.cmake"
          sccache --show-stats
      - name: Compile IBAMR
        id: build
        run: |
          bash -c "ctest -VV -S .github/cmake/ctest_build.cmake"
          sccache --show-stats
      - name: Test IBAMR
        id: test
        run: |
          bash -c "ctest --output-on-failure -VV -S .github/cmake/ctest_test.cmake"
      - name: Compile IBAMR examples
        id: examples
        run: |
          cd /build/ibamr
          make -j2 examples
          # 2 of 2: we have to upload something, might as well make it empty
          rm -rf ~/.cache/sccache
          mkdir -p ~/.cache/sccache
          sccache --show-stats

  # build IBAMR with autotools
  build_ibamr_autotools:
    runs-on: ubuntu-latest
    name: Build IBAMR (autotools)
    container:
      image: 'docker://dcthomp/ibamr:0.9-build-deps'
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
        id: git
      - name: Create keys
        id: keys
        run: |
          echo "::set-output name=key1::$(( ${{ github.run_number }} - 1))"
          echo "::set-output name=key2::$(( ${{ github.run_number }} - 2))"
          echo "::set-output name=key3::$(( ${{ github.run_number }} - 3))"
          echo "::set-output name=key4::$(( ${{ github.run_number }} - 4))"
          echo "::set-output name=key5::$(( ${{ github.run_number }} - 5))"
      - name: Populate sccache
        uses: actions/cache@v2
        env:
          cache-name: sccache
        id: cache
        with:
          path: ~/.cache/sccache
          # The same note on picking keys above applies here.
          key: ${{ runner.os }}-build-autotools-${{ github.run_number }}
          restore-keys: |
            ${{ runner.os }}-build-autotools-${{ steps.keys.outputs.key1 }}
            ${{ runner.os }}-build-autotools-${{ steps.keys.outputs.key2 }}
            ${{ runner.os }}-build-autotools-${{ steps.keys.outputs.key3 }}
            ${{ runner.os }}-build-autotools-${{ steps.keys.outputs.key4 }}
            ${{ runner.os }}-build-autotools-${{ steps.keys.outputs.key5 }}
            ${{ runner.os }}-build-autotools-
      - name: Start sccache server
        id: cache-server
        run: sccache --start-server
      - name: Configure IBAMR (autotools)
        id: configure
        run: |
          source /etc/profile.d/modules.sh
          module load mpi
          export CC="sccache $(which mpicc)"
          export CXX="sccache $(which mpic++)"
          # we are just compiling things so go for speed
          export CFLAGS="-O0"
          export CXXFLAGS="-O0"
          export FFLAGS="-O0"
          mkdir build
          cd build
          ../configure PETSC_DIR=/petsc/x86_64 --with-samrai=/samrai \
          --enable-libmesh --with-libmesh=/libmesh --with-libmesh-method=opt
          sccache --show-stats
      - name: archive
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: autotools-config.log
          path: build/config.log
      - name: Compile IBAMR (autotools)
        id: build
        run: |
          source /etc/profile.d/modules.sh
          module load mpi
          export CC="sccache $(which mpicc)"
          export CXX="sccache $(which mpic++)"
          echo "CC=${CC}"
          echo "CXX=${CXX}"
          cd build
          make -j 2 tests examples
          sccache --show-stats
